name: 'Adjust  CVSS'
description: 'Adjust the CVSS scores of CodeQL queries'
inputs:
  patterns:
    description: 'Score patterns'
    required: true
  input:
    description: 'Path to the input SARIF file'
    required: true
  output:
    description: 'Path to the output SARIF file'
    required: true
runs:
  using: "composite"
  steps:
    - name: adjust
      env:
        PATTERNS: ${{ inputs.patterns }}
      run: |
        unset LD_PRELOAD
        python3 "${{ github.action_path }}/adjust_cvss.py" --input "${{ inputs.input }}" --output "${{ inputs.output }}" --split-lines -- "$PATTERNS"
      shell: bash
